### ISSUE TITLE
Fix conversion of __file__ to unicode

### ISSUE THREAD

**Issue by mithro** [luci/luci-py#264]
Currently most of the code does this;
```python
ROOT_DIR = unicode(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
```
Which will fail with the following error when 
```python
tansell@tansell-z620-l2:~/work/☃/luci-py/client/tests$ python file_path_test.py 
Traceback (most recent call last):
  File "file_path_test.py", line 17, in <module>
    BASE_DIR = unicode(os.path.dirname(os.path.abspath(__file__)))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 36: ordinal not in range(128)
```

The correct way to do what this line is trying to do is;
```python
ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(
    __file__.decode(sys.getfilesystemencoding()))))
```

As you want all your paths to be unicode, we should probably also audit all the ROOT_DIR values to do this decoding too.

**Comment by mithro** [comment]
Here is the current output of the tests when running with a unicode character in your path;
```
Running presubmit commit checks ...
Running /usr/local/google/home/tansell/work/☃/luci-py/PRESUBMIT.py
Running /usr/local/google/home/tansell/work/☃/luci-py/client/PRESUBMIT.py
INFO:PRESUBMIT:Running pylint on 87 files

** Presubmit Messages **
Pylint (87 files using ['--disable=cyclic-import'] on 32 cores) (5.06s)

Pylint (87 files using ['--disable=all', '--enable=cyclic-import']) (5.85s)

libs/logdog/tests/bootstrap_test.py (0.05s)

libs/logdog/tests/stream_test.py (0.06s)

libs/logdog/tests/streamname_test.py (0.04s)

libs/logdog/tests/varint_test.py (2.59s)

tests/isolate_format_test.py (0.09s)

tests/isolate_smoke_test.py (6.53s)

tests/isolated_format_test.py (0.17s)

tests/large_test.py (3.70s)

tests/logging_utils_test.py (0.20s)

tests/lru_test.py (0.07s)

tests/net_test.py (0.16s)

tests/run_isolated_test.py (0.34s)

tests/subprocess42_test.py (6.59s)

tests/swarming_test.py (0.31s)

tests/threading_utils_test.py (0.74s)

tests/trace_inputs_smoke_test.py (0.09s)

tests/url_open_timeout_test.py (1.93s)

tests/zip_package_test.py (0.20s)

third_party/chromium/natsort_test.py (0.07s)

** Presubmit ERRORS **
tests/file_path_test.py (0.04s) failed
Traceback (most recent call last):
  File "tests/file_path_test.py", line 17, in <module>
    BASE_DIR = unicode(os.path.dirname(os.path.abspath(__file__)))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 36: ordinal not in range(128)


tests/isolate_test.py (0.07s) failed
Traceback (most recent call last):
  File "tests/isolate_test.py", line 17, in <module>
    ROOT_DIR = unicode(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 36: ordinal not in range(128)


tests/isolateserver_test.py (0.90s) failed
test_policies_active_trimming (__main__.DiskCacheTest) ... ok
test_policies_fit (__main__.DiskCacheTest) ... ok
test_policies_free_disk (__main__.DiskCacheTest) ... ok
test_policies_too_much (__main__.DiskCacheTest) ... ok
test_download_isolated (__main__.IsolateServerDownloadTest) ... ok
test_download_two_files (__main__.IsolateServerDownloadTest) ... FAIL
test_contains_format_failure (__main__.IsolateServerStorageApiTest) ... ok
test_contains_network_failure (__main__.IsolateServerStorageApiTest) ... ok
test_contains_success (__main__.IsolateServerStorageApiTest) ... ok
test_fetch_failure (__main__.IsolateServerStorageApiTest) ... ok
test_fetch_offset_bad_header (__main__.IsolateServerStorageApiTest) ... ok
test_fetch_offset_success (__main__.IsolateServerStorageApiTest) ... ok
test_fetch_success (__main__.IsolateServerStorageApiTest) ... ok
test_push_failure_finalize (__main__.IsolateServerStorageApiTest) ... ok
test_push_failure_upload (__main__.IsolateServerStorageApiTest) ... ok
test_push_success (__main__.IsolateServerStorageApiTest) ... ok
test_server_capabilities_success (__main__.IsolateServerStorageApiTest) ... ok
test_push_and_fetch (__main__.IsolateServerStorageSmokeTest) ... ok
test_push_and_fetch_gzip (__main__.IsolateServerStorageSmokeTest) ... ok
test_synchronous_push (__main__.IsolateServerStorageSmokeTest) ... ok
test_synchronous_push_gzip (__main__.IsolateServerStorageSmokeTest) ... ok
test_upload_items (__main__.IsolateServerStorageSmokeTest) ... ok
test_upload_items_gzip (__main__.IsolateServerStorageSmokeTest) ... ok
test_async_push (__main__.StorageTest) ... ok
test_async_push_generator_errors (__main__.StorageTest) ... ok
test_async_push_upload_errors (__main__.StorageTest) ... ok
test_batch_items_for_check (__main__.StorageTest) ... ok
test_get_missing_items (__main__.StorageTest) ... ok
test_upload_tree (__main__.StorageTest) ... ok
test_archive_directory (__main__.TestArchive) ... INFO:root:rmtree(/tmp/isolateserver8fXvYf)
DEBUG:root:make_tree_deleteable(/tmp/isolateserver8fXvYf)
INFO:root:rmtree(/tmp/isolateserverndePMx)
DEBUG:root:make_tree_deleteable(/tmp/isolateserverndePMx)
ok
test_archive_directory_envvar (__main__.TestArchive) ... INFO:root:rmtree(/tmp/isolateserver5gjjz9)
DEBUG:root:make_tree_deleteable(/tmp/isolateserver5gjjz9)
INFO:root:rmtree(/tmp/isolateserver7aqoJA)
DEBUG:root:make_tree_deleteable(/tmp/isolateserver7aqoJA)
ok
test_archive_duplicates (__main__.TestArchive) ... INFO:root:Waiting for all threads to die...
INFO:root:Done.
ok
test_archive_files (__main__.TestArchive) ... INFO:root:rmtree(/tmp/isolateserverBaTtbU)
DEBUG:root:make_tree_deleteable(/tmp/isolateserverBaTtbU)
ok
test_archive_no_server (__main__.TestArchive) ... ok
test_bad_zip_file (__main__.TestZipCompression)
Verify decompressing broken file raises IOError. ... ok
test_compress_and_decompress (__main__.TestZipCompression)
Test data === decompress(compress(data)). ... ok
test_zip_bomb (__main__.TestZipCompression)
Verify zip_decompress always returns small chunks. ... ok

======================================================================
FAIL: test_download_two_files (__main__.IsolateServerDownloadTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/isolateserver_test.py", line 839, in test_download_two_files
    self.assertEqual(expected, actual)
AssertionError: {'/usr/local/google/home/tansell/work/\xe2\x98\x83/luci-py/client/path/to/a': 'C [truncated]... != {u'/usr/local/google/home/tansell/work/\u2603/luci-py/client/path/to/a': 'Coucou [truncated]...
- {'/usr/local/google/home/tansell/work/\xe2\x98\x83/luci-py/client/path/to/a': 'Coucou',
?                                        ^^ ^^^^^^^

+ {u'/usr/local/google/home/tansell/work/\u2603/luci-py/client/path/to/a': 'Coucou',
?  +                                      ^ ^^

-  '/usr/local/google/home/tansell/work/\xe2\x98\x83/luci-py/client/path/to/b': 'Bye Bye'}
?                                        ^^ ^^^^^^^

+  u'/usr/local/google/home/tansell/work/\u2603/luci-py/client/path/to/b': 'Bye Bye'}
?  +                                      ^ ^^


----------------------------------------------------------------------
Ran 37 tests in 0.733s

FAILED (failures=1)


tests/on_error_test.py (0.92s) failed
test_shell_out_crash (__main__.OnErrorServerTest) ... FAIL
test_shell_out_crash_server_down (__main__.OnErrorServerTest) ... FAIL
test_shell_out_exception (__main__.OnErrorServerTest) ... FAIL
test_shell_out_exception_no_msg (__main__.OnErrorServerTest) ... FAIL
test_shell_out_hacked (__main__.OnErrorServerTest) ... ok
test_shell_out_report (__main__.OnErrorServerTest) ... FAIL
test_no_http (__main__.OnErrorTest) ... ok
test_report (__main__.OnErrorTest) ... ok

======================================================================
FAIL: test_shell_out_crash (__main__.OnErrorServerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/on_error_test.py", line 314, in test_shell_out_crash
    self.assertEqual(expected, re.sub(r' \d+', ' 0', out))
AssertionError: 'Traceback (most recent call last):\n  File "on_error_test.py", line 0, in <module>\n    sys.exit(run_shell_out(sys.argv[2], sys.argv[3]))\n  File "on_error_test.py", line 0, in run_shell_out\n    raise ValueError(\'Oops\')\nValueError: Oops\nSending the crash report ... done.\nReport URL: https://localhost/error/1234\nProcess exited due to exception\nOops\n' != 'Traceback (most recent call last):\n  File "on_error_test.py", line 0, in <module>\n    sys.exit(run_shell_out(sys.argv[2], sys.argv[3]))\n  File "on_error_test.py", line 0, in run_shell_out\n    raise ValueError(\'Oops\')\nValueError: Oops\nSending the crash report ...Error in atexit._run_exitfuncs:\nTraceback (most recent call last):\n  File "/usr/lib/python2.7/atexit.py", line 0, in _run_exitfuncs\n    func(*targs, **kargs)\n  File "/usr/local/google/home/tansell/work/\xe2\x98\x83/luci-py/client/utils/on_error.py", line 0, in _check_for_exception_on_exit\n    \'\'.join(traceback.format_tb(last_tb)))\n  File "/usr/local/google/home/tansell/work/\xe2\x98\x83/luci-py/client/utils/on_error.py", line 0, in _report_exception\n    \'env\': _serialize_env(),\n  File "/usr/local/google/home/tansell/work/\xe2\x98\x83/luci-py/client/utils/on_error.py", line 0, in _serialize_env\n    (k, v.encode(\'ascii\', \'replace\')) for k, v in os.environ.iteritems())\n  File "/usr/local/google/home/tansell/work/\xe2\x98\x83/luci-py/client/utils/on_error.py", line 0, in <genexpr>\n    (k, v.encode(\'ascii\', \'replace\')) for k, v in os.environ.iteritems())\nUnicodeDecodeError: \'ascii\' codec can\'t decode byte 0xe2 in position 0: ordinal not in range(128)\nError in sys.exitfunc:\nTraceback (most recent call last):\n  File "/usr/lib/python2.7/atexit.py", line 0, in _run_exitfuncs\n    func(*targs, **kargs)\n  File "/usr/local/google/home/tansell/work/\xe2\x98\x83/luci-py/client/utils/on_error.py", line 0, in _check_for_exception_on_exit\n    \'\'.join(traceback.format_tb(last_tb)))\n  File "/usr/local/google/home/tansell/work/\xe2\x98\x83/luci-py/client/utils/on_error.py", line 0, in _report_exception\n    \'env\': _serialize_env(),\n  File "/usr/local/google/home/tansell/work/\xe2\x98\x83/luci-py/client/utils/on_error.py", line 0, in _serialize_env\n    (k, v.encode(\'ascii\', \'replace\')) for k, v in os.environ.iteritems())\n  File "/usr/local/google/home/tansell/work/\xe2\x98\x83/luci-py/client/utils/on_error.py", line 0, in <genexpr>\n    (k, v.encode(\'ascii\', \'replace\')) for k, v in os.environ.iteritems())\nUnicodeDecodeError: \'ascii\' codec can\'t decode byte 0xe2 in position 0: ordinal not in range(128)\n'

======================================================================
FAIL: test_shell_out_crash_server_down (__main__.OnErrorServerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/on_error_test.py", line 358, in test_shell_out_crash_server_down
    self.assertEqual(expected, re.sub(r' \d+', ' 0', out))
AssertionError: 'Traceback (most recent call last):\n  File "on_error_test.py", line 0, in <module>\n    sys.exit(run_shell_out(sys.argv[2], sys.argv[3]))\n  File "on_error_test.py", line 0, in run_shell_out\n    raise ValueError(\'Oops\')\nValueError: Oops\nSending the crash report ... failed!\nProcess exited due to exception\nOops\n' != 'Traceback (most recent call last):\n  File "on_error_test.py", line 0, in <module>\n    sys.exit(run_shell_out(sys.argv[2], sys.argv[3]))\n  File "on_error_test.py", line 0, in run_shell_out\n    raise ValueError(\'Oops\')\nValueError: Oops\nSending the crash report ...Error in atexit._run_exitfuncs:\nTraceback (most recent call last):\n  File "/usr/lib/python2.7/atexit.py", line 0, in _run_exitfuncs\n    func(*targs, **kargs)\n  File "/usr/local/google/home/tansell/work/\xe2\x98\x83/luci-py/client/utils/on_error.py", line 0, in _check_for_exception_on_exit\n    \'\'.join(traceback.format_tb(last_tb)))\n  File "/usr/local/google/home/tansell/work/\xe2\x98\x83/luci-py/client/utils/on_error.py", line 0, in _report_exception\n    \'env\': _serialize_env(),\n  File "/usr/local/google/home/tansell/work/\xe2\x98\x83/luci-py/client/utils/on_error.py", line 0, in _serialize_env\n    (k, v.encode(\'ascii\', \'replace\')) for k, v in os.environ.iteritems())\n  File "/usr/local/google/home/tansell/work/\xe2\x98\x83/luci-py/client/utils/on_error.py", line 0, in <genexpr>\n    (k, v.encode(\'ascii\', \'replace\')) for k, v in os.environ.iteritems())\nUnicodeDecodeError: \'ascii\' codec can\'t decode byte 0xe2 in position 0: ordinal not in range(128)\nError in sys.exitfunc:\nTraceback (most recent call last):\n  File "/usr/lib/python2.7/atexit.py", line 0, in _run_exitfuncs\n    func(*targs, **kargs)\n  File "/usr/local/google/home/tansell/work/\xe2\x98\x83/luci-py/client/utils/on_error.py", line 0, in _check_for_exception_on_exit\n    \'\'.join(traceback.format_tb(last_tb)))\n  File "/usr/local/google/home/tansell/work/\xe2\x98\x83/luci-py/client/utils/on_error.py", line 0, in _report_exception\n    \'env\': _serialize_env(),\n  File "/usr/local/google/home/tansell/work/\xe2\x98\x83/luci-py/client/utils/on_error.py", line 0, in _serialize_env\n    (k, v.encode(\'ascii\', \'replace\')) for k, v in os.environ.iteritems())\n  File "/usr/local/google/home/tansell/work/\xe2\x98\x83/luci-py/client/utils/on_error.py", line 0, in <genexpr>\n    (k, v.encode(\'ascii\', \'replace\')) for k, v in os.environ.iteritems())\nUnicodeDecodeError: \'ascii\' codec can\'t decode byte 0xe2 in position 0: ordinal not in range(128)\n'

======================================================================
FAIL: test_shell_out_exception (__main__.OnErrorServerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/on_error_test.py", line 230, in test_shell_out_exception
    out = self.call(httpd.url, 'exception', 0)
  File "tests/on_error_test.py", line 177, in call
    self.assertEqual(returncode, proc.returncode)
AssertionError: 0 != 1

======================================================================
FAIL: test_shell_out_exception_no_msg (__main__.OnErrorServerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/on_error_test.py", line 265, in test_shell_out_exception_no_msg
    out = self.call(httpd.url, 'exception_no_msg', 0)
  File "tests/on_error_test.py", line 177, in call
    self.assertEqual(returncode, proc.returncode)
AssertionError: 0 != 1

======================================================================
FAIL: test_shell_out_report (__main__.OnErrorServerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/on_error_test.py", line 199, in test_shell_out_report
    out = self.call(httpd.url, 'report', 0)
  File "tests/on_error_test.py", line 177, in call
    self.assertEqual(returncode, proc.returncode)
AssertionError: 0 != 1

----------------------------------------------------------------------
Ran 8 tests in 0.758s

FAILED (failures=5)


tests/run_isolated_smoke_test.py (0.04s) failed
Traceback (most recent call last):
  File "tests/run_isolated_smoke_test.py", line 13, in <module>
    ROOT_DIR = unicode(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 36: ordinal not in range(128)


tests/trace_inputs_test.py (0.04s) failed
Traceback (most recent call last):
  File "tests/trace_inputs_test.py", line 13, in <module>
    BASE_DIR = unicode(os.path.dirname(os.path.abspath(__file__)))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 36: ordinal not in range(128)


Presubmit checks took 17.7s to calculate.
```

**Comment by mithro** [comment]
I've uploaded a patch which fixes the problem at https://codereview.chromium.org/2093593002/
