### ISSUE TITLE
net.py HttpService doesn't renegociate xsrf token after expiration

### ISSUE THREAD

**Issue by GoogleCodeExporter** [luci/luci-py#91]
```
upload log is here:
https://uberchromegw.corp.google.com/i/chromeos/builders/daisy%20canary/builds/2
551/steps/DebugSymbols/logs/stdio

but the key points:
 - the system starts off fine:
20:19:54: INFO: Checking existence of 100 files...
20:19:54: INFO: Starting new HTTPS connection (1): isolateserver.appspot.com
20:19:55: INFO: Protocol version: 1.0
20:19:55: INFO: Server version: 562-61d9774
20:19:59: INFO: Queried 100 files, 3 cache hit
20:20:00: INFO: Checking existence of 100 files...
20:20:00: INFO: Queried 100 files, 5 cache hit
20:20:00: INFO: Checking existence of 100 files...
20:20:02: INFO: Queried 100 files, 6 cache hit
20:20:03: INFO: Starting new HTTPS connection (1): isolateserver.appspot.com
20:20:03: INFO: Checking existence of 100 files...
...

 - every line like below means the system has posted that file to the isolateserver (btw, the timing info is relative to the crash server, not isolate, so don't be surprised by those):
20:21:20: INFO: upload of       5210 bytes took 0:00:15.530764: libxt_tcp.so.sym

 - after a while, this shows up:
22:19:54: INFO: upload of      19506 bytes took 0:00:00.536612: setresuid01.sym
22:19:55: WARNING: Authentication is required for 
https://isolateserver.appspot.com/content-gs/store/chromium-os-upload-symbols/f0
927155e9b4487d844a7686eb13325c2f0178c8?... on attempt 0.
403 Client Error: Forbidden
Cookie authentication requires interactive login
22:19:55: ERROR: Unable to authenticate to https://isolateserver.appspot.com 
(403 Client Error: Forbidden). Use auth.py to login: python auth.py login 
--service=https://isolateserver.appspot.com
22:19:55: WARNING: posting fc-match.sym to dedupe server failed
Traceback (most recent call last):
  File "/b/cbuild/daisy-canary-master/chromite/scripts/upload_symbols.py", line 370, in SymbolDeduplicatorNotify
    storage.push(item, item.content(0))
  File "/b/cbuild/daisy-canary-master/chromite/third_party/swarming.client/isolateserver.py", line 995, in push
    item.digest, item.push_state.upload_url))
IOError: Failed to upload a file f0927155e9b4487d844a7686eb13325c2f0178c8 to 
https://isolateserver.appspot.com/content-gs/store/chromium-os-upload-symbols/f0
927155e9b4487d844a7686eb13325c2f0178c8?...
22:19:55: INFO: upload of       2248 bytes took 0:00:00.674036: fc-match.sym
```

Original issue reported on code.google.com by `vapier@chromium.org` on 18 Mar 2014 at 5:26

**Comment by maruel** [comment]
This code was reimplemented.
